workflows:
  ios-swiftly:
    name: ios_toim
    environment:
      vars:
        XCODE_WORKSPACE: "OpenIMSDKUIKit.xcworkspace"
        XCODE_SCHEME: "OpenIMSDKUIKit_Example"
        FCI_BUILD_DIR: "$HOME/clone/Example/"
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd $FCI_BUILD_DIR
          pod install

      - name: Build iOS project (unsigned)
        script: |
          cd $FCI_BUILD_DIR
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Debug \
                     -destination 'generic/platform=iOS Simulator' \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     clean build

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - user1@example.com
        notify:
          success: true
          failure: true
