workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: io.toim.cn
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa
    artifacts:
      - build/ios/ipa/*.ipa
