workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      cocoapods: default
    scripts:
      - name: Install pods
        script: |
          cd Example
          pod install
      - name: Build
        script: |
          cd Example
          xcode-project build-ipa --workspace "OpenIMSDKUIKit.xcworkspace" --scheme "OpenIMSDKUIKit_Example"
    artifacts:
      - build/ios/ipa/*.ipa
